[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["nikhilkalige <nikhilkalige@gmail.com>"]
edition = "2018"

[dependencies]
aoc_derive = { path= "./aoc_derive" }
aoc = { path= "./aoc" }
itertools = "0.9.0"


[workspace]
members = ["aoc_derive"]
